### ISSUE TITLE
not supported rank icon?

### ISSUE THREAD

**Issue by NiceCats** [DenverCoder1/DenverCoder1#14]
Hi, I love what you have done with the github stats. But when I follow what you have done and adding rank_icon=github, its seems not supported?

**Comment by DenverCoder1** [comment]
I deployed a fork of the repository a while ago that is not necessarily up to date with every commit from the upstream version.

You should be using https://github-readme-stats.vercel.app or your own deployment as the base url and not the deployment I made at https://denvercoder1-github-readme-stats.vercel.app

**Comment by NiceCats** [comment]
Thank you, It work with the upstream version 😊
